### ISSUE TITLE
Cannot stop by Ctrl+C on Windows

### ISSUE THREAD

**Issue by k-tamura** [jetty-project/embedded-jetty-jsp#12]
This application cannot stop by <kbd>Ctrl</kbd>+<kbd>C</kbd> on Windows.

Steps to reproduce:

1.  Run the following commands:

		C:\Users\ktamura\git> git clone https://github.com/jetty-project/embedded-jetty-jsp.git
		C:\Users\ktamura\git> cd embedded-jetty-jsp
		C:\Users\ktamura\git\embedded-jetty-jsp> mvn clean package
		C:\Users\ktamura\git\embedded-jetty-jsp> mvn exec:exec

2.  Click <kbd>Ctrl</kbd>+<kbd>C</kbd>.
-> Jetty does not stop.

Environment:

	C:\Users\ktamura\git\embedded-jetty-jsp> mvn -version
	Apache Maven 3.2.2 (45f7c06d68e745d05611f7fd14efb6594181933e; 2014-06-17T22:51:42+09:00)
	Maven home: C:\apache-maven-3.2.2\bin\..
	Java version: 1.8.0_131, vendor: Oracle Corporation
	Java home: C:\Program Files\Java\jdk1.8.0_131\jre
	Default locale: ja_JP, platform encoding: MS932
	OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by joakime** [comment]
Works fine with Windows 10 using Maven 3.6.0 and AdoptOpenJDK 8u252
