### ISSUE TITLE
How to pre-compile the JSP?

### ISSUE THREAD

**Issue by dipdeb** [jetty-project/embedded-jetty-jsp#262]
Not an issue, but I want to know how to pre-compile the JSP using maven.
Have read about jspc, but not able to figure out how to use it in this case.

**Comment by olamy** [comment]
Hi
Have a look here https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#jetty-jspc-maven-plugin

**Comment by dipdeb** [comment]
> Hi Have a look here https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#jetty-jspc-maven-plugin

Have tried it but not able to make it work with this example

**Comment by joakime** [comment]
> Have tried it but not able to make it work with this example

We need some more information.
Show us your pom.xml, and any kind of warning / error messages you get from the attempt.
An example project that isn't working for you would be great (just fork this project, make the changes you want to do, and then give us the URL to your fork)

**Comment by dipdeb** [comment]
> > Have tried it but not able to make it work with this example
> 
> We need some more information. Show us your pom.xml, and any kind of warning / error messages you get from the attempt. An example project that isn't working for you would be great (just fork this project, make the changes you want to do, and then give us the URL to your fork)

Sorry, for the late reply.
In this https://github.com/dipdeb/embedded-jetty-jsp-precompiled, which is taken from embedded-jetty-jsp, I have tried to pre-compile the jsp files. For the sake of simplicity I have taken only one jsp page here and also added web.xml; since I want to merge the generated web.xml with an old one. I have changed the jetty startup part to support JSP. 
When I run `mvn clean package` the jsp code is getting compiled and webfrag.xml is also generated alongwith new web.xml; but the attribute `webXml` which is used to transfer the newly created web.xml to the `src/main/resources/webroot/WEB-INF` is not working. My primary goal is to take only the compiled jsp classes and other classes to the production environment.

**Comment by joakime** [comment]
Note: this repository is going to be archived.
The role of this repository is being taken over by https://github.com/jetty/jetty-examples
Unfortunately, we cannot move this issue to the new repository issue tracker.
Feel free to reopen this at the new location if you still need help.
