### ISSUE TITLE
Can you please provide a demo project for embedded-jetty-jsp for Java 11?

### ISSUE THREAD

**Issue by wangvic** [jetty-project/embedded-jetty-jsp#34]
Hi,

This demo project is so useful. It helped me to upgrade from Jetty 8.1 to 9.4. 

However, the runtime isn't working after I upgraded to JDK 11. I think it's something to do with the StandardJarScanner class.

Can you please provide an example of code that works in both Java 8 and Java 11? Thank you.

**Comment by lachlan-roberts** [comment]
@wangvic I can run this demo successfully with both JDK8 and JDK11.
What errors are you getting when you attempt to run the project?

**Comment by joakime** [comment]
This project also builds and tests (successfully) with JDK8 and JDK11 with each commit and pull request too.

**Comment by joakime** [comment]
There is now also branches for Jetty 9.4.x, 10.0.x, and 11.0.x.
