### ISSUE TITLE
Sample project does not work with latest jetty release

### ISSUE THREAD

**Issue by phaas** [jetty-project/embedded-jetty-jsp#4]
This project breaks in (at least) two ways when running with the latest Jetty release.

Steps:
 - Change the version in pom.xml: `<jetty-version>9.2.6.v20141205</jetty-version>`

Expected result:
 - Application starts up when launching `org.eclipse.jetty.demo.Main`
 - JSTL TLDs are found and supported in `http://localhost:8080/test/jstl.jsp`

Actual results:
 - Application often fails to start up due to value of `javax.servlet.context.tempdir`
 - Application fails to locate TLDs, is unable to compile JSP page.

Temporary File Error
-----------------------------
The sample application is configured to use the same temporary directory for each startup. During initialization the temporary directory is first deleted, then recreated. Occasionally the directory does not actually exist after dir.mkdirs() is called.
```
[WARNING] WebAppContext: Failed startup of context o.e.j.w.WebAppContext@1c2c22f3{/,file:/C:/Users/Patrick/workspace/embedded-jetty-jsp/target/classes/webroot/,null}
java.lang.IllegalStateException: Temp dir C:\Users\Patrick\AppData\Local\Temp\embedded-jetty-jsp not useable: writeable=false, dir=false
	at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:384)
	at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:271)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:69)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:464)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:500)
```

JSP Error
--------------
```
Problem accessing /test/jstl.jsp. Reason:

    Server Error
Caused by:

org.apache.jasper.JasperException: The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application
```
The latest version of Jetty attempts to pre-scan for TLDs (`org.eclipse.jetty.webapp.MetaInfConfiguration`), which may not actually find any TLDs. In this case, the context attribute `org.eclipse.jetty.tlds` is set to an empty set.

The `org.eclipse.jetty.apache.jsp.JettyJasperInitializer.newTldScanner(ServletContext, boolean, boolean, boolean)` method will check this attribute and, if it's not null, exclusively use these TLDs.

In this sample application, the MetaInfConfiguration does not find any TLDs as it's not provided with any JARs. The JettyJasperInitializer erroneously bypasses the Jasper TLD scan that would otherwise find the TLDs.

I suspect that this is a regression caused by this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=443262

**Comment by janbartel** [comment]
phaas,

I've just committed changes to bring the embedded-jetty-examples up-to-date
with jetty-9.2.6. Please try it out. As regards the tmpdir problem, that's
a separate issue I'll look into later.

Jan

On 4 January 2015 at 02:52, phaas <notifications@github.com> wrote:

> This project breaks in (at least) two ways when running with the latest
> Jetty release.
>
> Steps:
>
>    - Change the version in pom.xml:
>    <jetty-version>9.2.6.v20141205</jetty-version>
>
> Expected result:
>
>    - Application starts up when launching org.eclipse.jetty.demo.Main
>    - JSTL TLDs are found and supported in
>    http://localhost:8080/test/jstl.jsp
>
> Actual results:
>
>    - Application often fails to start up due to value of
>    javax.servlet.context.tempdir
>    - Application fails to locate TLDs, is unable to compile JSP page.
>
> Temporary File Error
>
> The sample application is configured to use the same temporary directory
> for each startup. During initialization the temporary directory is first
> deleted, then recreated. Occasionally the directory does not actually exist
> after dir.mkdirs() is called.
>
> [WARNING] WebAppContext: Failed startup of context o.e.j.w.WebAppContext@1c2c22f3{/,file:/C:/Users/Patrick/workspace/embedded-jetty-jsp/target/classes/webroot/,null}
> java.lang.IllegalStateException: Temp dir C:\Users\Patrick\AppData\Local\Temp\embedded-jetty-jsp not useable: writeable=false, dir=false
>     at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:384)
>     at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:271)
>     at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:69)
>     at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:464)
>     at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:500)
>
> JSP Error
>
> Problem accessing /test/jstl.jsp. Reason:
>
>     Server Error
> Caused by:
>
> org.apache.jasper.JasperException: The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application
>
> The latest version of Jetty attempts to pre-scan for TLDs (
> org.eclipse.jetty.webapp.MetaInfConfiguration), which may not actually
> find any TLDs. In this case, the context attribute org.eclipse.jetty.tlds
> is set to an empty set.
>
> The org.eclipse.jetty.apache.jsp.JettyJasperInitializer.newTldScanner(ServletContext,
> boolean, boolean, boolean) method will check this attribute and, if it's
> not null, exclusively use these TLDs.
>
> In this sample application, the MetaInfConfiguration does not find any
> TLDs as it's not provided with any JARs. The JettyJasperInitializer
> erroneously bypasses the Jasper TLD scan that would otherwise find the TLDs.
>
> I suspect that this is a regression caused by this bug:
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=443262
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jetty-project/embedded-jetty-jsp/issues/4>.
>



-- 
Jan Bartel <janb@intalio.com>
www.webtide.com
'Expert Jetty/CometD developer,production,operations advice'

**Comment by janbartel** [comment]
Actually, the tmp dir problem is likely a windows-specific issue. I only
have linux here. So can you please take a look into this on your system?
When the error occurs, does the directory already exist or not? Does it
have any content in it? Are you keeping the directory there by having one
of the files in it open, eg in an editor?

regards
Jan

On 8 January 2015 at 12:37, Jan Bartel <janb@intalio.com> wrote:

> phaas,
>
> I've just committed changes to bring the embedded-jetty-examples
> up-to-date with jetty-9.2.6. Please try it out. As regards the tmpdir
> problem, that's a separate issue I'll look into later.
>
> Jan
>
> On 4 January 2015 at 02:52, phaas <notifications@github.com> wrote:
>
>> This project breaks in (at least) two ways when running with the latest
>> Jetty release.
>>
>> Steps:
>>
>>    - Change the version in pom.xml:
>>    <jetty-version>9.2.6.v20141205</jetty-version>
>>
>> Expected result:
>>
>>    - Application starts up when launching org.eclipse.jetty.demo.Main
>>    - JSTL TLDs are found and supported in
>>    http://localhost:8080/test/jstl.jsp
>>
>> Actual results:
>>
>>    - Application often fails to start up due to value of
>>    javax.servlet.context.tempdir
>>    - Application fails to locate TLDs, is unable to compile JSP page.
>>
>> Temporary File Error
>>
>> The sample application is configured to use the same temporary directory
>> for each startup. During initialization the temporary directory is first
>> deleted, then recreated. Occasionally the directory does not actually exist
>> after dir.mkdirs() is called.
>>
>> [WARNING] WebAppContext: Failed startup of context o.e.j.w.WebAppContext@1c2c22f3{/,file:/C:/Users/Patrick/workspace/embedded-jetty-jsp/target/classes/webroot/,null}
>> java.lang.IllegalStateException: Temp dir C:\Users\Patrick\AppData\Local\Temp\embedded-jetty-jsp not useable: writeable=false, dir=false
>>     at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:384)
>>     at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:271)
>>     at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:69)
>>     at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:464)
>>     at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:500)
>>
>> JSP Error
>>
>> Problem accessing /test/jstl.jsp. Reason:
>>
>>     Server Error
>> Caused by:
>>
>> org.apache.jasper.JasperException: The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application
>>
>> The latest version of Jetty attempts to pre-scan for TLDs (
>> org.eclipse.jetty.webapp.MetaInfConfiguration), which may not actually
>> find any TLDs. In this case, the context attribute org.eclipse.jetty.tlds
>> is set to an empty set.
>>
>> The org.eclipse.jetty.apache.jsp.JettyJasperInitializer.newTldScanner(ServletContext,
>> boolean, boolean, boolean) method will check this attribute and, if it's
>> not null, exclusively use these TLDs.
>>
>> In this sample application, the MetaInfConfiguration does not find any
>> TLDs as it's not provided with any JARs. The JettyJasperInitializer
>> erroneously bypasses the Jasper TLD scan that would otherwise find the TLDs.
>>
>> I suspect that this is a regression caused by this bug:
>> https://bugs.eclipse.org/bugs/show_bug.cgi?id=443262
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jetty-project/embedded-jetty-jsp/issues/4>.
>>
>
>
>
> --
> Jan Bartel <janb@intalio.com>
> www.webtide.com
> 'Expert Jetty/CometD developer,production,operations advice'
>



-- 
Jan Bartel <janb@intalio.com>
www.webtide.com
'Expert Jetty/CometD developer,production,operations advice'

**Comment by phaas** [comment]
Hi Jan,

Thanks for looking at this! I've tried the latest version and it's working as expected now. I see now how to configure the ContainerIncludeJarPattern.

I'll give this a try in my app.

I'm not sure what's going on exactly with the directory not found issue -- it must be something windows specific. I'll see if I can come up with a minimal test case. When I debugged it previously, I recall seeing the folder getting created/delete and then again deleted/created. Somehow that sequence of actions results in the JVM not having a working file handle.

**Comment by phaas** [comment]
I've had some more time to look at the container/server configuration. The include pattern seemed overly specific to me, calling out exactly the JARs that happened to contain tlds in this project.

Since my ultimate goal is to build an application that can be deployed as a single jar file (via the `maven-shade-plugin` I suspected that this setting would not work once the JAR files were merged. A quick test with the pom.xml configuration below confirmed that. However, expanding the expression to match either ".*" or ".*jar$|.*/classes/.*" worked fine for this use cases.

Reviewing the related section in the manual helped me understand why jetty makes the distinction between container and webapp jars.

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-shade-plugin</artifactId>
	<version>1.6</version>
	<configuration>
		<createDependencyReducedPom>true</createDependencyReducedPom>
		<filters>
			<filter>
				<artifact>*:*</artifact>
				<excludes>
					<exclude>META-INF/*.SF</exclude>
					<exclude>META-INF/*.DSA</exclude>
					<exclude>META-INF/*.RSA</exclude>
				</excludes>
			</filter>
		</filters>
	</configuration>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>shade</goal>
			</goals>
			<configuration>
				<transformers>
					<transformer
						implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
					<transformer
						implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
						<mainClass>org.eclipse.jetty.demo.Main</mainClass>
					</transformer>
				</transformers>
			</configuration>
		</execution>
	</executions>
</plugin>
```

```
mvn clean install
java -jar target\embedded-jetty-jsp-1-SNAPSHOT-shaded.jar
```

**Comment by phaas** [comment]
A final note on the temp dir issue.

I've put together a minimal test case and the odd behavior only happens when a "Windows Explorer" is watching the %TEMP% directory (the parent of the "embedded-jetty-jsp" folder) and when JSP files are accessed (which are created under jsp/org/apache/jsp/test/..)

The jetty startup steps attempt to delete the directory and all sub-directories and recreate it. In some scenarios this fails, and the JVM is only able to remove a single directory from the hierarchy.

I wasn't able to reproduce the issue once the "explorer" task was closed.

**Comment by tioteath** [comment]
Have the same issue with `solr-5.2.1`, can't update to 5.3.x as it has compatibility issues.
