### ISSUE TITLE
How to run using java

### ISSUE THREAD

**Issue by dipdeb** [jetty-project/embedded-jetty-jsp#40]
Hi @joakime 
This is not an issue, but I would like to know how to run this embedded-jetty-jsp in the production environment or using
java -jar uber.jar or fatjar like this https://github.com/jetty-project/embedded-jetty-uber-jar?
I've tried adding the shade as shown in the the above link, the webapp is coming up but when accessing the jsp pages
getting the jasperexception error.

**Comment by lachlan-roberts** [comment]
@dipdeb this is working fine for me, take a look at my the branch i just made, and try it out.
https://github.com/jetty-project/embedded-jetty-uber-jar/tree/jetty-10.0.x-debugging

it demonstrates running a JSP both with `ServletContextHandler` and with `WebAppContext`

**Comment by dipdeb** [comment]
I'm able to make it work by adding the shade plugin.
