### ISSUE TITLE
How can I enable support JSP with embedded Jetty 7?

### ISSUE THREAD

**Issue by bangph** [jetty-project/embedded-jetty-jsp#5]
Hi, I'm using embedded Jetty 7 to support Java JDK 1.6+, it works very good but without JSP support, how can I do this as now I always have this problem:

HTTP ERROR 500

Problem accessing index.jsp. Reason:

```
JSP support not configured
```

Here is my jetty.jar 

https://drive.google.com/a/fimo.edu.vn/file/d/0B_VL2-SVlKPHQ0FQaTRCdGM0M0U/view?usp=sharing

**Comment by joakime** [comment]
You know that [Jetty 7 is EOL (End of Life)](https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00069.html) right?

**Comment by bangph** [comment]
Thanks, I already know about this. But it doesn't mean embedded Jetty 7 cannot support JSP, right? I think one who developed embedded Jetty 6+ will know the answer as I've pointed out I cannot change to Jetty 9 which need Java 8 to execute.

**Comment by joakime** [comment]
Jetty 6 is worlds different than Jetty 7.  (Its like comparing Mac OS 9 to Mac OS 10)

Jetty 9.2.x line is still a Java 7 requirement (and still has releases), but starting in Jetty 9.3 its Java 8+

What environment are you stuck with Java 7 on?

(The most common answer to this is "Android", and if that's your answer, then you will have little to none success with JSP on Android,  Android's Java-like environment is not compatible as JSP requires very specific classloader setups and normal bytecode, but Android forces classloader and requires dex or art compiled classes.  Even JSP pre-compile is hit or miss.)

**Comment by bangph** [comment]
It looks good for me now when I know Jetty 9.2 still use Java 1.7 to run. We use Linux OS and use Java 1.6 as it is much popular for all users and not relate to Android. So I will appreciate if you can help me to make embedded Jetty 7 support JSP. I've searched a lot in Google but they only have guide to support JSP with standard Jetty 7 (download JSP library and run as option with start.jar) http://blog.max.berger.name/2010/01/enabling-jsp-support-in-jetty-7.html

**Comment by bangph** [comment]
Hi, I've found out how to do this by myself. By adding the jar library like apache.jaspser, logging.Factory and common.ExpressionEvaluatorImpl inside jetty.jar and now it is working as I want to see.

**Comment by joakime** [comment]
You **really need** to upgrade your Java VM.

You know that Java 1.7 is considered expired and EOL by Oracle, right?
