### ISSUE TITLE
How Can I do the same using the XML Configuration?

### ISSUE THREAD

**Issue by atapas** [jetty-project/embedded-jetty-jsp#6]
First of all, great work. This gives a very good direction. Best read I found so far.

I am embedding Jetty 9.3.5 but all the configurations are done in various xmls like jetty.xml, jetty-deploy, jetty-jmx etc.

What will be the xml configurations of the equivalent that is in Main.java? Specially this part:

        context.setAttribute("org.eclipse.jetty.containerInitializers", jspInitializers());
        context.setAttribute(InstanceManager.class.getName(), new SimpleInstanceManager());
        context.addBean(new ServletContainerInitializersStarter(context), true);
        context.setClassLoader(getUrlClassLoader());

**Comment by joakime** [comment]
Using XML configurations?   

Then just include the `--module=jsp` in your `${jetty.base}/start.ini` and you are done.  

Enabling JSP is easy in Jetty distribution.

**Comment by atapas** [comment]
Thank You for the response. I am using jetty embedded to my app.

Yes I have these files in my ${jetty.base}:  jetty-deploy.xml,  jetty-https.xml,  jetty-jmx-remote.xml,  jetty-jmx.xml, jetty-ssl-context.xml,  jetty-ssl.xml,  jetty.xml,  `start.ini`  and webdefault.xml

I have provided `--module=jsp` in start.ini file (This is the only line I have in it). I have added the jars in class path but I get this error:

`org.apache.jasper.JasperException: PWC6349: Cannot find a java compiler for compilation.  If running with JDK 5 or before, Ant or JDT compiler can be used, if the corresponding jars and bridge classes (org.apache.jasper.compiler.AntJavaCompiler or org.apache.jasper.compiler.JDTJavaCompiler) are included
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:92)`


When I set,

 <Call class="java.lang.System"  name="setProperty">
              <Arg>org.apache.jasper.compiler.disablejsr199</Arg>
              <Arg>false</Arg>
   </Call>

The scriptlet in JSP Fail to compile.

Not sure, what I am missing..

FYI, I have upgraded Jetty from 8.1 to 9.3.5.

**Comment by joakime** [comment]
ok, so this has nothing to do with the `embedded-jetty-jsp` project here on github.

Your questions are about jetty-distribution, and from your questions it appears that you are trying to use Jetty 9 like you did with Jetty 8.    That's going to cause you **lots of extra work** doing it that way.

Its important to know that Jetty 9 uses a `${jetty.home}` and `${jetty.base}` split directory structure now.
And its all based on module enablement and properties.

Also of note, the `org.apache.jasper.compiler.disablejsr199` is a remnant of the old Jetty 8 (and WAY BUGGY) Glassfish Jasper implementation.   Jetty 9 has moved towards the Tomcat Jasper implementation, which doesn't use this property/attribute.

Lets start from the beginning.

 1. Download jetty-distribution - http://download.eclipse.org/jetty/
 2. Unpack your jetty-distribution into a directory of its own.  This is now your `${jetty.home}` directory.
 3. Do not edit, delete, rename, modify, move, touch or change anything in the `${jetty.home}` directory, ever.
 4. Now create a new blank directory somewhere else, this will become your `${jetty.base}` directory.
 5. Your `${jetty.base}` directory will be where all of your instance specific configuration, webapps, logs, resources, extra libraries, and more live.
 6. You can manually initialize that directory by manually creating a `start.ini` and a few directories, or you can have the `start.jar` from the jetty-distribution do some of the work for you.
 7. Example commands:
```shell
$ cd /path/to/my-base
$ java -jar /path/to/jetty-dist/start.jar --add-to-start=http,deploy,jsp,annotations,logging
  .. status of start.ini initialization here ..
$ java -jar /path/to/jetty-dist/start.jar --list-config
  .. output of your configuration here ..
$ cp /path/to/compiled/webapps/mywebapp.war /path/to/my-base/webapps/
$ java -jar /path/to/jetty-dist/start.jar
  .. startup of your instance here ..
```

You now have a configured Jetty instance, suitable for JSP usage.  For further help, use either the jetty-users mailing list or stackoverflow, not this specific issue tracker.
